### PR TITLE
Add case-class-companion incompatibility

### LINKED ISSUE #122: New incompatibility: case class companions don’t extend Function anymore
In Scala 2, a case class companion was extending Function.

~~~ scala
case class Foo(x: Int, b: Boolean)

// The Scala 2 compiler synthesizes the following companion
object Foo extends Function2[Int, Boolean, Foo] {
  def apply(x: Int, b: Boolean) = new Foo(x, b)
}
~~~

This is not the case anymore, which means that companions don’t inherit function methods such as `apply`, `tupled`, `andThen`, and `compose`.

One work-around to write code that cross-compiles is to manually write a function that calls the constructor:

~~~ scala
val fooConstructor: (Int, Boolean) => Foo = (x, b) => Foo(x, b)
// Then, `fooConstructor` has all the methods of Function
~~~

### PR DESCRIPTION
**Pull request by adpi2**
Fixes #122

### CODE REVIEW

**Review by julienrf — APPROVED** [review]
Nice workaround, thanks Adrien!

**Comment by julienrf** [comment]
I wonder if https://github.com/lampepfl/dotty/pull/7207 fixed the problem?

**Comment by adpi2** [comment]
All the incompatibilities in the migration guide are tested. We check that the `scala-2.13/<incompat>.scala` source file compiles in  2.13 but not in 3.0.0-M3. Also we check that the `scala/<incompat>.scala` source file compiles in both 2.13 and 3.0.0-M3.

**Comment by julienrf** [comment]
We will see after the migration to 3.0.0-RC1 if the incompatibility is still incompatible :)

**Comment by adpi2** [comment]
Apparently it does not fix the problem.

Indeed, all the incompatibilities in this repo, including this one are tested. We check that the `scala-2.13/<incompat>.scala` source file compiles in  2.13 but not in 3.0.0-M3. Also we check that the `scala/<incompat>.scala` source file compiles in both 2.13 and 3.0.0-M3.

I think the PR you mention allows to write this:
```scala
Foo.apply.tupled((1,true))
Foo.apply.curried(2)(false)
```
But this doesn't compile in 2.13 because the eta-expansion only occurs when a function type is expected.

**Pull request merged**
